- routes.yaml
* Add healthcheck endpoint to routes.yaml
> DSND-1253 Add healthcheck endpoint to routes.yaml

- src/main/resources/application.properties
* Corrects some values in application properties regarding spring management endpoints
> DSND-1253 Correct application properties

- src/main/java/uk/gov/companieshouse/exemptions/EricTokenAuthenticationFilter.java
- src/main/java/uk/gov/companieshouse/exemptions/WebSecurityConfig.java
* Without this filter requests to the health check endpoint would return 401 unauthorised
> DSND-1263 Add empty auth filter for healthcheck endpoint

- src/main/java/uk/gov/companieshouse/exemptions/Config.java
- src/main/java/uk/gov/companieshouse/exemptions/DummyController.java
- src/main/java/uk/gov/companieshouse/exemptions/EricTokenAuthenticationFilter.java
- src/main/java/uk/gov/companieshouse/exemptions/ExemptionsApplication.java
- src/main/java/uk/gov/companieshouse/exemptions/WebSecurityConfig.java
* Add dummy upsert endpoint
* Add authentication filter
[DSND-1258](https://companieshouse.atlassian.net/browse/DSND-1258)
> DSND-1258 Add dummy upsert endpoint

- src/main/java/uk/gov/companieshouse/exemptions/MongoDbConfig.java
- src/main/java/uk/gov/companieshouse/exemptions/ServiceUnavailableException.java
*  Add mongoDbConfig to remove _class property from mongo
> DSND-1259 Add mongoDbConfig to remove _class property from mongo

- mvnw.cmd
- routes.yaml
- src/main/java/uk/gov/companieshouse/exemptions/CompanyExemptionsDocument.java
- src/main/java/uk/gov/companieshouse/exemptions/ExceptionHandlerConfig.java
- src/main/java/uk/gov/companieshouse/exemptions/ExemptionsController.java
- src/main/java/uk/gov/companieshouse/exemptions/ExemptionsService.java
- src/main/java/uk/gov/companieshouse/exemptions/ExemptionsServiceImpl.java
- src/main/java/uk/gov/companieshouse/exemptions/ServiceUnavailableException.java
- src/test/java/uk/gov/companieshouse/exemptions/ExemptionsControllerTest.java
- src/test/java/uk/gov/companieshouse/exemptions/ExemptionsServiceImplTest.java
* Add get mapping to the controller
* Implement get exemptions service method
* Change get endpoint URI
[DSND-1260](https://companieshouse.atlassian.net/browse/DSND-1260)
> DSND-1260 Implement get company exemptions request

- src/main/java/uk/gov/companieshouse/exemptions/ExemptionsApiService.java
- src/main/java/uk/gov/companieshouse/exemptions/ExemptionsController.java
- src/main/java/uk/gov/companieshouse/exemptions/ExemptionsService.java
- src/main/java/uk/gov/companieshouse/exemptions/ExemptionsServiceImpl.java
- src/main/java/uk/gov/companieshouse/exemptions/ResourceChangedRequestMapper.java
- src/test/java/uk/gov/companieshouse/exemptions/ExemptionsControllerTest.java
- src/test/java/uk/gov/companieshouse/exemptions/ExemptionsServiceImplTest.java
- src/test/java/uk/gov/companieshouse/exemptions/ResourceChangedRequestMapperTest.java
* Add delete endpoint to controller
* Implement service logic for delete endpoint
* Refactor upsert company exemptions logic to be consistent with delete logic
[DSND-1270](https://companieshouse.atlassian.net/browse/DSND-1270)
> DSND-1270 Implement delete endpoint

- routes.yaml
* Change routes.yaml weight to less than company-profile-api
> DSND-1406 - Change route weight to less than company-profile-api

- routes.yaml
Reverts companieshouse/company-exemptions-data-api#14
> Revert "DSND-1406 - Change route weight to less than company-profile-api"

- routes.yaml
* Changes route for GET endpoint to match on exactly 8 characters rather than any string.
[DSND-1406](https://companieshouse.atlassian.net/browse/DSND-1406)
> DSND-1406 Add more specific regex for company number in routes.yaml

- src/feature/java/uk/gov/companieshouse/exemptions/exemptions/ExemptionsSteps.java
- src/main/java/uk/gov/companieshouse/exemptions/AuthenticationFilter.java
- src/test/java/uk/gov/companieshouse/exemptions/AuthenticationFilterTest.java
- src/test/java/uk/gov/companieshouse/exemptions/ExemptionsControllerTest.java
* Authorise OAUTH2 requests only if they are GET requests
* Authorise KEY requests only if they have internal app privileges or if they are GET requests
[DSND-1545](https://companieshouse.atlassian.net/browse/DSND-1545)
[DSND-1545]: https://companieshouse.atlassian.net/browse/DSND-1545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1545 Add authorisation for eric key privileges

- pom.xml
- src/feature/java/uk/gov/companieshouse/exemptions/exemptions/ExemptionsSteps.java
- src/feature/resources/features/exemptions/upsert_exemptions.feature
- src/feature/resources/fragments/requests/exemptions_api_request_out_of_date.json
- src/main/java/uk/gov/companieshouse/exemptions/ExemptionsRepository.java
- src/main/java/uk/gov/companieshouse/exemptions/ExemptionsServiceImpl.java
- src/main/java/uk/gov/companieshouse/exemptions/WebSecurityConfig.java
- src/test/java/uk/gov/companieshouse/exemptions/ExemptionsServiceImplTest.java
* Compares the delta_at field within the request body to the delta_at field within the existing document, for the specified company number, if one exists.
* Improve test coverage in unit and integration tests.
[DSND-1578](https://companieshouse.atlassian.net/browse/DSND-1578)
[DSND-1578]: https://companieshouse.atlassian.net/browse/DSND-1578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-1578 Compare deltas using delta_at fields

- src/main/java/uk/gov/companieshouse/exemptions/service/ExemptionsApiService.java
- src/test/java/uk/gov/companieshouse/exemptions/service/ExemptionsApiServiceTest.java
> bug: modify CHANGED_RESOURCE_URI to include private

- src/main/java/uk/gov/companieshouse/exemptions/config/Config.java
- src/main/java/uk/gov/companieshouse/exemptions/controller/ExemptionsController.java
- src/main/java/uk/gov/companieshouse/exemptions/util/DateUtils.java
- src/main/java/uk/gov/companieshouse/exemptions/util/ResourceChangedRequestMapper.java
- src/test/java/uk/gov/companieshouse/exemptions/util/ResourceChangedRequestMapperTest.java
* Add new DateUtils class
* Refactor supplied in Config
* Update mapper and tests
* Locally tested, all passes.
Resolves [BI-13964](https://companieshouse.atlassian.net/browse/BI-13964)
[BI-13964]: https://companieshouse.atlassian.net/browse/BI-13964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-13964: Update published_at timestamp

- terraform/groups/ecs-service/main.tf
- terraform/groups/ecs-service/profiles/live-eu-west-2/live/vars
- terraform/groups/ecs-service/profiles/staging-eu-west-2/staging/vars
- terraform/groups/ecs-service/variables.tf
[DSND-3057](https://companieshouse.atlassian.net/browse/DSND-3057)
[DSND-3057]: https://companieshouse.atlassian.net/browse/DSND-3057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-3057: Increase task count

- pom.xml
This seems to be the cause of the security-check job failing on concourse.
[DSND-3020](https://companieshouse.atlassian.net/browse/DSND-3020)
[DSND-3020]: https://companieshouse.atlassian.net/browse/DSND-3020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-3020: Update version of spring-webmvc

- pom.xml
- src/feature/java/uk/gov/companieshouse/exemptions/exemptions/ExemptionsSteps.java
- src/main/java/uk/gov/companieshouse/exemptions/util/DateUtils.java
* Update internal dependencies
* Update spring and jib maven plugin dependencies
* Remove test containers bom
Resolves [BI-14123](https://companieshouse.atlassian.net/browse/BI-14123)
[BI-14123]: https://companieshouse.atlassian.net/browse/BI-14123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-14123: Set published at format to use 24hr time

- src/feature/java/uk/gov/companieshouse/exemptions/exemptions/ExemptionsSteps.java
- src/main/java/uk/gov/companieshouse/exemptions/config/Config.java
- src/main/java/uk/gov/companieshouse/exemptions/config/WebSecurityConfig.java
- src/main/java/uk/gov/companieshouse/exemptions/controller/ControllerExceptionHandler.java
- src/main/java/uk/gov/companieshouse/exemptions/controller/ExemptionsController.java
- src/main/java/uk/gov/companieshouse/exemptions/logging/DataMapHolder.java
- src/main/java/uk/gov/companieshouse/exemptions/logging/RequestLoggingFilter.java
- src/main/java/uk/gov/companieshouse/exemptions/model/ResourceChangedRequest.java
- src/main/java/uk/gov/companieshouse/exemptions/service/AuthenticationFilter.java
- src/main/java/uk/gov/companieshouse/exemptions/service/ExemptionsApiService.java
- src/main/java/uk/gov/companieshouse/exemptions/service/ExemptionsService.java
- src/main/java/uk/gov/companieshouse/exemptions/service/ExemptionsServiceImpl.java
- src/main/java/uk/gov/companieshouse/exemptions/util/LocalDateDeSerializer.java
- src/main/java/uk/gov/companieshouse/exemptions/util/ResourceChangedRequestMapper.java
- src/test/java/uk/gov/companieshouse/exemptions/controller/ExemptionsControllerTest.java
- src/test/java/uk/gov/companieshouse/exemptions/service/ExemptionsApiServiceTest.java
- src/test/java/uk/gov/companieshouse/exemptions/service/ExemptionsServiceImplTest.java
- src/test/java/uk/gov/companieshouse/exemptions/util/ResourceChangedRequestMapperIT.java
- src/test/java/uk/gov/companieshouse/exemptions/util/ResourceChangedRequestMapperTest.java
* Implemented data map holder and logging filter
* Add DataMapHolder to all logger calls
* Ensure logger defined statically in all instances
* Remove unnecessary passing of context id
* Update log messages for clarity and brevity
Resolves [DSND-2874](https://companieshouse.atlassian.net/browse/DSND-2874)
[DSND-2874]: https://companieshouse.atlassian.net/browse/DSND-2874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2874: Update structured logging

- pom.xml
- src/main/java/uk/gov/companieshouse/exemptions/exception/ServiceUnavailableException.java
* Have ServiceUnavailableException extend a RuntimeException to ensure it is handled correctly
Resolves [DSND-2874](https://companieshouse.atlassian.net/browse/DSND-2874)
[DSND-2874]: https://companieshouse.atlassian.net/browse/DSND-2874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2874: Fix handling of kafka invocation error

- src/main/java/uk/gov/companieshouse/exemptions/service/ExemptionsServiceImpl.java
Resolves [DSND-2874](https://companieshouse.atlassian.net/browse/DSND-2874)
[DSND-2874]: https://companieshouse.atlassian.net/browse/DSND-2874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DSND-2874: Add data log map to stale delta error msg
